/**
 * Mã lỗi API — khớp `shared/messages/error-codes.js` (BE).
 * FE map sang `api_errors.<CODE>` trong messages/vi.json.
 */
export const API_ERROR_CODES = {
  SYSTEM: {
    VALIDATION_ERROR: 'STD_SYS_004',
  },
  VALIDATION: {
    CONTENT_REQUIRED: 'STD_VAL_001',
  },
  AUTH: {
    EMAIL_EXISTS: 'STD_AUT_011',
    USERNAME_EXISTS: 'STD_AUT_012',
    INVALID_CREDENTIALS: 'STD_AUT_013',
    USER_INACTIVE_OR_BANNED: 'STD_AUT_014',
    MISSING_TOKEN: 'STD_AUT_020',
    INVALID_OR_EXPIRED_TOKEN: 'STD_AUT_021',
    REFRESH_TOKEN_EXPIRED: 'STD_AUT_022',
    REFRESH_TOKEN_REVOKED: 'STD_AUT_023',
  },
  QUESTION: {
    NOT_FOUND: 'STD_QTN_001',
    FORBIDDEN: 'STD_QTN_002',
    CLOSED: 'STD_QTN_003',
  },
  ANSWER: {
    NOT_FOUND: 'STD_ANS_001',
    FORBIDDEN: 'STD_ANS_002',
    TARGET_NOT_FOUND: 'STD_ANS_004',
  },
  QUIZ: {
    SUBJECT_NOT_FOUND: 'STD_QIZ_001',
    TOPIC_NOT_FOUND: 'STD_QIZ_002',
    TOPIC_SUBJECT_MISMATCH: 'STD_QIZ_003',
    NOT_ENOUGH_QUESTIONS: 'STD_QIZ_004',
    INVALID_QUIZ_QUESTION: 'STD_QIZ_005',
    ATTEMPT_NOT_FOUND: 'STD_QIZ_006',
    FORBIDDEN_ATTEMPT: 'STD_QIZ_007',
    EMPTY_ANSWERS: 'STD_QIZ_008',
    ATTEMPT_ALREADY_SUBMITTED: 'STD_QIZ_009',
    ATTEMPT_NOT_IN_PROGRESS: 'STD_QIZ_010',
    INCOMPLETE_ANSWERS: 'STD_QIZ_011',
    ATTEMPT_NOT_SUBMITTED: 'STD_QIZ_012',
    SET_NOT_FOUND: 'STD_QIZ_013',
    SET_NOT_PUBLISHED: 'STD_QIZ_014',
    SET_EMPTY: 'STD_QIZ_015',
    ATTEMPT_TIMED_OUT: 'STD_QIZ_016',
  },
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES][keyof (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]];

const API_ERROR_CODE_PATTERN = /^STD_[A-Z0-9_]+$/;

export const isApiErrorCode = (value: string): boolean => API_ERROR_CODE_PATTERN.test(value);
